name: neost
channels:
        - defaults
        - conda-forge
dependencies:
        - numpy <= 1.26.4
        - cython ~= 0.29
        - matplotlib
        - scipy
        - pymultinest
        - multinest
        - pytest
        - numba
        - seaborn
        - corner
        - gsl
        - kalepy
