name: NEoST
channels:
        - defaults
        - conda-forge
dependencies:
        - python # Just to ensure we're not using system-wide python. See PEP 668
        - numpy
        - cython
        - matplotlib
        - scipy
        - pymultinest
        - multinest
        - pytest
        - numba
        - seaborn
        - corner
        - gsl
        - kalepy
